import {Injectable} from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Ais } from './model/Ais';


const reqHeader = new HttpHeaders({'Authorization':'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJIVEZ6dEgxZDUwWGdmdV96aERBWm9MS0RhSkItbTBDWGtCclRyeHJDZW1NIn0.eyJqdGkiOiI4M2UwYTdjNy05N2Y1LTRhNjItYTA3Ny01ZTcxYmUzNDQ3YWMiLCJleHAiOjE1NDQ3MTE1MjYsIm5iZiI6MCwiaWF0IjoxNTQ0NzA4NTI2LCJpc3MiOiJodHRwOi8vMTAuMjAwLjEwLjE6MTgwODAvYXV0aC9yZWFsbXMvc2FtcGxlIiwiYXVkIjoid2ViZGVjbGFyYXRpb24td2ViLWNsaWVudCIsInN1YiI6IjVlMWVhMTlhLTA1OWUtNDA2YS04NDhhLTc4NDhjNTkwOWFkMyIsInR5cCI6IkJlYXJlciIsImF6cCI6IndlYmRlY2xhcmF0aW9uLXdlYi1jbGllbnQiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiI5ZTdkYzNkNy1mYjE2LTQwMWUtOTJlMy1hMTJlMGRlN2Q1ZTciLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJ3ZWJkZWNsYXJhdGlvbi1zZXJ2aWNlIjp7InJvbGVzIjpbImRlbGV0ZS1haXMiLCJzZWFyY2gtYWlzIiwic2VhcmNoLXNpdGUiLCJkZWxldGUtc2l0ZSIsImNvdW50LXNpdGUiLCJyZWFkLWFpcyIsImNvdW50LWFpcyIsInNhdmUtc2l0ZSIsInNhdmUtYWlzIiwibGlzdC1haXMiLCJsaXN0LXNpdGUiLCJyZWFkLXNpdGUiXX0sIndlYmRlY2xhcmF0aW9uLXdlYi1jbGllbnQiOnsicm9sZXMiOlsiZGVsZXRlLWFpcyIsInNlYXJjaC1haXMiLCJzZWFyY2gtc2l0ZSIsImRlbGV0ZS1zaXRlIiwiY291bnQtc2l0ZSIsInJlYWQtYWlzIiwiY291bnQtYWlzIiwibGlzdC1haXMiLCJzYXZlLXNpdGUiLCJsaXN0LXNpdGUiLCJyZWFkLXNpdGUiLCJzYXZlLWFpcyJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwibmFtZSI6InVzZXIwMSB1c2VyMDEiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ1c2VyMDEiLCJnaXZlbl9uYW1lIjoidXNlcjAxIiwiZmFtaWx5X25hbWUiOiJ1c2VyMDEiLCJlbWFpbCI6InVzZXIwMUBzaWNwYS1kZXYuY29tIn0.G9SeK5PLDbpoiTeGX5dps1dxelByhodZiS0f7fYhXdDvJtA3scBDu5vF66GKb7fgujJLViqWZeL7InpQGzKS_YWWK26dNVRZGtwyaiXpTxxqMNOJcTIPqTnoboO7iyBSBOf9mHSkNPcbG69gCpoCtguwb8UsIOoQ55AEJeExVc6gWLn6ZYsYfnlh7bjgcC4ax-6JSTQom2KZs8u7yBWfxdw5ZrxDr3Ecq5PN5iBkLkO8gRSilvtToc5JuwSLfmpsRUPe-FmejSj1pkb1ujM_aaE_KPgYLP6vz-hrPMuL_bpF-cXo5uSpGgERWceOurEh365tT_iHr85EgwbTqdhGDg'
})



@Injectable({
  providedIn: 'root'
})
export class DataService {

  constructor(private http:HttpClient) { }

  // Uses http.get() to load data from a single API endpoint
  getAisData() {
    return this.http.get<Ais[]>('http://10.200.10.1:8080/api/v1/ais/test123', { headers: reqHeader });
}
  
}
